### ISSUE TITLE
Missing detection of envvars via auto_envvar_prefix-option

### ISSUE THREAD

**Issue by PatrikHlobil** [click-contrib/sphinx-click#105]
Dear maintainers,

I first wish to thank you for your project. I love click and the abilility to autogenerate the CLI documentation.

As you show in your documentation, sphinx-click automatically detects explicitly passed environment variables like:
```python
@greet.command()
@click.argument('user', envvar='USER')
def hello(user):
    """Greet a user."""
    click.echo('Hello %s' % user)
```

There is however no support for the detection of auto-generated envvars like in:
```python
@greet.command(context_settings={"auto_envvar_prefix": "HELLO"},)
@click.argument('user')
def hello(user):
    """Greet a user."""
    click.echo('Hello %s' % user)
```

which can use the environment variable `HELLO_USER` for passing the user argument.

I looked at your code, but I am not familiar enough with the internals of click and sphinx to easily see how I could add this feature.

Best Patrik

**Comment by stephenfin** [comment]
TIL. I didn't know this was a thing but [the docs prove it is](https://click.palletsprojects.com/en/7.x/options/#dynamic-defaults-for-prompts). This would be a near enhancement if anyone wanted to work on this. If not, I'll find time eventually.
