### ISSUE TITLE
Extend \b rewrapping to click options

### ISSUE THREAD

**Issue by marekvi95** [click-contrib/sphinx-click#106]
We use \b to prevent rewrapping also in click options. There's a workaround in sphinx-click to append '|' when there's a line containing \b, but this workaround is missing for click.options and we receive warnings during sphinx build because of bad indentation.
Please could you extend this also for click options?

Click 8.1.2
sphinx-click 4.1.0
Python 3.9.5

```python
def _format_option(opt: click.Option) -> ty.Generator[str, None, None]:
    opt_help = _get_help_record(opt)

    yield ".. option:: {}".format(opt_help[0])
    if opt_help[1]:
        yield ""
        bar_enabled = False
        for line in statemachine.string2lines(
            ANSI_ESC_SEQ_RE.sub("", opt_help[1]), tab_width=4, convert_whitespace=True
        ):
            if line == "\b":
                bar_enabled = True
                continue
            if line == "":
                bar_enabled = False
            line = "| " + line if bar_enabled else line

            yield _indent(line)
```

**Comment by stephenfin** [comment]
Could you give me an example of a command with an option using `\b` (for test purposes)?
