### ISSUE TITLE
Unicode issue on imports

### ISSUE THREAD

**Issue by readmodifywrite** [click-contrib/sphinx-click#11]
This is on Python 2.7.13, click 6.6, sphinx 1.6.2, sphinx-click 1.0.2

`ClickDirective._load_module` (`ext.py` line 188) is getting a unicode value for module path.  This causes `__import__` to raise `"TypeError: Item in ``from list'' must be str, not unicode"`.

The fix is easy, one can just do:

```
module_path = str(module_path)
```

I'd be happy to make a pull request for this, however, I'm not sure if this would cause issues with Python 3.

**Comment by stephenfin** [comment]
I'd be happy to review and test and PR on Python 3. Fire away, if you can

**Comment by alisaifee** [comment]
:+1: I am facing this issue as well. I can verify that this does not cause any problems with Python3.
