### ISSUE TITLE
Supports `.. click:example::` and `.. click:run::` directives

### ISSUE THREAD

**Issue by kdeldycke** [click-contrib/sphinx-click#110]
The canonical `click` documentation has a nice way of showing CLI code examples and their results by the way of custom `.. click:example::` and `.. click:run::` Sphinx directives.

See for instance how [plain Python is wrapped with `click:example`](https://github.com/pallets/click/blob/main/docs/quickstart.rst#basic-concepts---creating-a-command) and [rendered as a syntax-highlighted block](https://click.palletsprojects.com/en/8.1.x/quickstart/#basic-concepts-creating-a-command). The resulting call of that CLI is automatically executed and rendered by a simple reference to `click:run`.

This is powerful the same way [`doctest`](https://docs.python.org/3/library/doctest.html#module-doctest) is, as it serves the dual purpose of documentation and testing (Sphinx will not compile on errors). It reduces the burden of maintaining up-to-date examples.

This issue is a proposition to add these directive to the `sphinx-click` project. With a name like this, it seems `sphinx-click` is the best home for this feature.

**Comment by kdeldycke** [comment]
These 2 directives are currently [implemented by the `Pallets-Sphinx-Themes` project](https://github.com/pallets/pallets-sphinx-themes/blob/7b69241f1fde3cc3849f513a9dd83fa8a2f36603/src/pallets_sphinx_themes/themes/click/domain.py#L256-L259).

Here is how I just managed to use them in my [`click-extra` project](https://github.com/kdeldycke/click-extra):
1. [Add `Pallets-Sphinx-Themes` dependency](https://github.com/kdeldycke/click-extra/blob/67f92f46c861666dfac5ef9408486d2940496f64/pyproject.toml#L83)
1. Add a little [workaround in Sphinx's `conf.py`](https://github.com/kdeldycke/click-extra/blob/67f92f46c861666dfac5ef9408486d2940496f64/docs/conf.py#L99-L106)
1. And now you can [use both `.. click:example::` and `.. click:run::` in your docs](https://github.com/kdeldycke/click-extra/commit/9031b7c83bc106f3105603f3c849b0e8a9e48b2e#diff-abe1e09771cc949a765515b0f1ae2d0c4a6ab90fceae133c7ea3efdc49fb65a6R121-R147).

Note that both directives needs to resides in the same `{eval-rst}` MyST block.

It's kind of hackish but OK to me for the moment. By adding these directives to `sphinx-click` we can get rid of the somewhat awkward `Pallets-Sphinx-Themes` dependency.

**Comment by stephenfin** [comment]
No issues with adding these here but I'd rather not duplicate it and it seems the pallets folks are happy with them where they are. Perhaps a pointer in the README would be useful?

I'm going to close this as I don't think there's anything to be done here. If you'd like to duplicate the changes here or add said link to the README, please feel free to reopen this.

**Comment by kdeldycke** [comment]
OK no worries, I understand. And the pallets folks provided the feedback I was waiting for, so let's keep that issue closed.

Thanks @stephenfin for the reply! :)
