### ISSUE TITLE
Sphinx_click not working with Read The Docs

### ISSUE THREAD

**Issue by Yarroudh** [click-contrib/sphinx-click#122]
I'm trying to create documentation for a CLI application using sphinx_click. When I build the docs locally using RDT template, I can see the CLI commands with their parameters, options and arguments but once I compile the docs in Read The Docs, the commands do not appear, all I have is an empty page with the header.

**Comment by stephenfin** [comment]
You need to enable installing the package under test. The [RTD documentation has a guide for this](https://docs.readthedocs.io/en/stable/faq.html#how-do-i-add-additional-software-dependencies-for-my-documentation).
