### ISSUE TITLE
Conversion of restructured text to ANSI colored output in terminal

### ISSUE THREAD

**Issue by hakonhagland** [click-contrib/sphinx-click#135]
Hi, I have started creating a helper module for sphinx_click. I wondered if someone could here could review it?
Here is the link: https://github.com/hakonhagland/sphinx-click-rst-to-ansi-formatter

See also: https://github.com/pallets/click/issues/1208

**Comment by stephenfin** [comment]
I don't think there's anything actionable here for me. If you'd like to propose a PR (docs or code), please do.
