### ISSUE TITLE
Missing tag for 5.2.2

### ISSUE THREAD

**Issue by dvzrv** [click-contrib/sphinx-click#140]
Hi! :wave: 

I package this project for Arch Linux. We rely on the auto-generated source tarballs of this repository.
Unfortunately there is no tag for 5.2.2 and therefore I am unable to upgrade.

Please create the tag (and ideally publish to PyPI based on it).

**Comment by stephenfin** [comment]
I'm not sure how that got out. I've yanked the release from PyPI and will publish a 5.3.0/6.0.0 shortly.
