### ISSUE TITLE
Click commands docstring in Sphinx format

### ISSUE THREAD

**Issue by azmeuk** [click-contrib/sphinx-click#142]
sphinx-click allows to build Sphinx documentation from click command docstrings, and this is great.
However, if one uses Sphinx directives in a click command docstring, then the command help flag will display the raw Sphinx code instead of the rendered code, and that sucks.

I wondered if there was a way to render the CLI docstrings with the [Sphinx text builder](https://www.sphinx-doc.org/en/master/usage/builders/index.html) before there are displayed in a terminal.

I opened a bug here, as using sphinx-click makes it appealing to use Sphinx directive in command docstrings, but maybe this would the scope of another `click-sphinx-docstrings` package?

What do you think?

**Comment by hakonhagland** [comment]
@azmeuk See also #135.

**Comment by azmeuk** [comment]
I can't believe I did not see this one among the 11 issues :/
Anyways, thank you, this is exactly what I needed.
