### ISSUE TITLE
Formatting is not working from Markdown doc pages

### ISSUE THREAD

**Issue by fedorov** [click-contrib/sphinx-click#146]
I tried to use `sphinx-click` within an .md page in the documentation, and could not make it work. 

This is the code:

```
.. click:: idc_index.cli:idc
  :prog: idc
  :nested: full
```

The formatting would always show up as below (verbatim):

```
download-from-selection
Download from a selection of collection(s), patient(s), study(studies) and series.

The filtering will be applied in sequence by first selecting the collection(s), followed by patient(s), study(studies) and series. If no filtering is applied, all the files will be downloaded.

.. program:: idc download-from-selection .. code-block:: shell

idc download-from-selection [OPTIONS]
.. rubric:: Options

.. option:: –download-dir <download_dir>
```

Switching the documentation page format to .rst resolved the issue.

For the reference, source code: https://github.com/ImagingDataCommons/idc-index/blob/main/docs/cli_tools.rst, documentation page: https://idc-index.readthedocs.io/en/latest/cli_tools.html.

**Comment by stephenfin** [comment]
We don't test against Markdown files and I've never personally used that feature of Sphinx, but I would be very surprised if you could use directives in exactly the same manner in Markdown as you do in reStructuredText. Maybe it's possible but the syntax is almost certainly different. I think a web search and/or trawl through StackOverflow is in order.
