### ISSUE TITLE
Support duplicate 'envvar' parameters

### ISSUE THREAD

**Issue by adamtheturtle** [click-contrib/sphinx-click#26]
Our use case is to have an option which is common to multiple commands.
This option has an `envvar` parameter.
This gives a warning.
I think that this is a valid, not warning-worthy error.
Perhaps `sphinx-click` should differentiate the built environment variable blocks somehow.

A small reproducible case follows:

`hello.py`:

```python
import click

@click.command()
@click.option('--foo', envvar='EXAMPLE')
def A(foo):
    pass

@click.command()
@click.option('--foo', envvar='EXAMPLE')
def B(foo):
    pass
```

`source/index.rst`:

```rst
.. click:: hello:A
   :prog: hello

.. click:: hello:B
   :prog: hello
```

Building the docs shows the following error:

```
hello:1: WARNING: Duplicate explicit target name: "cmdoption-hello--foo".
/Users/dev/Workspace/sphinx-envvar/source/index.rst:3: WARNING: Duplicate ID: "envvar-EXAMPLE".
```

Found with @mhrabovcin.

**Comment by stephenfin** [comment]
Seems there was another issue here. I've resolved this in 1.4.1.
