### ISSUE TITLE
'Hidden' commands still have their documentation auto-generated

### ISSUE THREAD

**Issue by james-ennis** [click-contrib/sphinx-click#31]
Click 7.0 allows us to declare commands as 'hidden', by defining something along the lines of:
```
@cli.command(short_help="Foo some bar", hidden=True)
@click.argument('bar')
@click.pass_obj
def foobar(bar):
    click.echo("Bar foo'd")
```

Notice the 'hidden=True'.

Now, if this command exists as a subcommand of a higher level command, when generating documentation for the higher level command, this sub command will appear within the documentation.
Please see this [downstream issue](https://gitlab.com/BuildStream/buildstream/issues/879) for a more specific example.

Ideally, hidden commands should not be present within the generated documentation.

**Comment by hutchins** [comment]
I actually would like to use this to create documentation on hidden commands for internal company usage. Is there an option to have it render hidden commands too?
