### ISSUE TITLE
Cross-referencing options

### ISSUE THREAD

**Issue by buzz** [click-contrib/sphinx-click#37]
I'm trying to cross-reference a CLI option:

```rst
.. click:: mypackage.cli:cli
  :prog: myprog
```

My CLI looks something like this:

```python
[...]
click.option("-v", "--verbose", is_flag=True, help="Print verbose messages.")
def cli(verbose, force, extensions, output_dir, source_dir):
    [...]
```

I tried <code>:option:\`--verbose\`</code> and also <code>:option:\`-v\`</code> which both should work [according to Sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option).

If I use it *after* the ``click:: mypackage.cli:cli`` everything works as expected.

If I use it *before* it, the compilation of the docs fail with:

```
Warning, treated as error:
/.../docs/usage.rst:29:unknown option: --verbose
```

Not sure though if this is a) a problem how I'm using Sphinx, b) problem in Sphinx or c) problem in sphinx-click.

Any help highly appreciated! Thx

### Versions

Python-3.7
click-7.0
sphinx-click-2.0.1
sphinx-2.0.0

Great project btw! :+1:

**Comment by stephenfin** [comment]
I'm guessing this is a Sphinx problem, to be honest. Can you reproduce if you use the `program` directive in raw form? If so, that proves it.

**Comment by buzz** [comment]
Just did that. And it turns out it's a Sphinx problem.

Opened issue there: https://github.com/sphinx-doc/sphinx/issues/6221
