### ISSUE TITLE
Support for sphinx v2

### ISSUE THREAD

**Issue by a-recknagel** [click-contrib/sphinx-click#39]
Sphinx v2.0.0 was released a month ago, and has since started to be been adopted into build chains. When sphinx-click is build from the current master, it works with sphinx without any issues, as far as I have tested. But to actually use it in production, I'd need to get it from pypi instead of building it.

Could a new version be build from the current master and be released to pypi?

**Comment by stephenfin** [comment]
Good call. Will do this shortly.

**Comment by a-recknagel** [comment]
Thanks a bunch!

**Comment by stephenfin** [comment]
2.1.0 is going through Travis at the moment and should be available shortly. Thanks for bringing this to my attention.
