### ISSUE TITLE
Documentation should better explain use of ':commands:' directive option

### ISSUE THREAD

**Issue by FunkyLoveCow** [click-contrib/sphinx-click#42]
I have a CLI that has many different subcommands. I want to document them individually. However, I have multiple available options at both the command and subcommand level. Example:

    cli --configfile ~/config.ini --json showdata --id 456

The subcommand here, `showdata` has only one option (`--id`), however, if I use `show-nested` and `commands` = `showdata`, I get generated content that shows all of the options for `cli` too:

- configfile
- json

This is annoying, as every subcommand has these same options, so it is repeated every time I want to document a subcommand. I only want to see the documentation for the subcommands (in this case, `--id`). 

How can I show ONLY the subcommand documentation? I'll document the parent options on their own.

If this isn't possible, can we add a new flag like `:show-nested:`, to do this?

**Comment by FunkyLoveCow** [comment]
Related to this:

If I attempt to break things out like this, I get lots of warnings because those top level options are duplicated, so I have errors like this:

```
cli:1: WARNING: Duplicate explicit target name: "cmdoption-cli--version".
cli:1: WARNING: Duplicate explicit target name: "cmdoption-cli--configfile".
cli:1: WARNING: Duplicate explicit target name: "cmdoption-cli--json".
```

**Comment by stephenfin** [comment]
Good idea. Hopefully I'll have some time to look at this in the next few weeks, but if anyone comes up with something before that, go for it 🙂

**Comment by FunkyLoveCow** [comment]
I tried to figure out how to make this change. It seems I don't know enough about docutils though. :( I appreciate you getting to this @stephenfin . Sorry I can't be more help than pointing out a problem though.

**Comment by stephenfin** [comment]
What version of the packages are you using for this? I can't reproduce it locally and the behavior I'm seeing is what you're looking for. For example, the [`git-pw` docs render as expected](https://patchwork.readthedocs.io/projects/git-pw/en/latest/usage/). I'm using Sphinx 1.8.5 and sphinx-click 2.1.0, though I also tried with sphinx-click 1.4.1 and had no issues there either.

**Comment by FunkyLoveCow** [comment]
I have uploaded a sample project: https://github.com/FunkyLoveCow/sample_cli_test

The generated documentation is also uploaded.

Packages:

```
Sphinx                        2.1.1     
sphinx-click                  2.2.0     
sphinx-rtd-theme              0.4.3     
```

This project has two subcommands - `group1` and `group2`. Each subcommand has at least 1 command and options. The main project (`sample_cli`) also has a few options.

---

This project has two usage pages. The first (`usage/all.rst`) has this documentation block:

```
.. click:: sample_cli.cli:sample_cli
    :prog: sample-cli
    :show-nested:
```

This generated documentation that shows the two `sample_cli` options only 1 time (as expected). 

---

The second page (`usage/individual.rst`) calls out the two subcommands one at a type by providing the `:commands:` directive. That page looks like this:

```
Group 1
~~~~~~~

.. click:: sample_cli.cli:sample_cli
    :prog: sample-cli
    :show-nested:
    :commands: group1

Group 2
~~~~~~~

.. click:: sample_cli.cli:sample_cli
    :prog: sample-cli
    :show-nested:
    :commands: group2
```

Within each of these it shows the options for both `sample_cli` and for the associated subcommand. So, on this page, it is showing the same section multiple times (the `sample_cli` options). This also generates warnings due to duplicate IDs 

---

My problems are with the second section. 

- Problem 1: The duplicate IDs break the Table of Contents, because the links example "sample-cli" for all subcommands and will take you to the first documented command. 
- Problem 2: The "sample_cli" options are documented for each code block. This is unwanted in my case because it shows for each block that is generated. I have multiple instances of the `--environment` and the `--user` options being documented

**Comment by stephenfin** [comment]
Ah, you're using it wrong :smile: This is what you want:

```
diff --git a/docs/usage/individual.rst b/docs/usage/individual.rst
index 5f6e97a..ce1835a 100644
--- a/docs/usage/individual.rst
+++ b/docs/usage/individual.rst
@@ -6,18 +6,19 @@ Usage - Individual
 
 This page is going to show individual subcommands one at a time
 
+.. click:: sample_cli.cli:sample_cli
+     :prog: sample-cli
+
 Group 1
 ~~~~~~~
 
-.. click:: sample_cli.cli:sample_cli
-    :prog: sample-cli
+.. click:: sample_cli.commands.group1:group1
+    :prog: sample-cli group1
     :show-nested:
-    :commands: group1
 
 Group 2
 ~~~~~~~
 
-.. click:: sample_cli.cli:sample_cli
-    :prog: sample-cli
+.. click:: sample_cli.commands.group2:group2
+    :prog: sample-cli group2
     :show-nested:
-    :commands: group2
```

In summary, we're showing the top level command without the `:show-nested:` argument and then we're showing each individual group by itself, with an updated `prog` since that isn't auto-discoverable.

The `:commands:` argument is intended to provide a way to exclude some commands you don't want to document. It's not intended as a way to show some sub-commands in one place and the others in another place since, as you've seen, this would still result in us documenting the top-level command twice. Perhaps we should point this out in the docs? I'd love a pull request to describe this, if so.

**Comment by FunkyLoveCow** [comment]
This is perfect! Thank you so much. I completely misunderstood how to do this. Your explanation was incredibly helpful.
