### ISSUE TITLE
Name of the click file

### ISSUE THREAD

**Issue by tedweishiwang** [click-contrib/sphinx-click#46]
I am running into a very weird issue. The documentation is fine for sphinx-click when the file name is `hello_world.py` or `a.py`, but when the name is changed to let's say `ted.py`, it would not work. Can anyone help me with that?

**Comment by stephenfin** [comment]
Can you provide a minimal reproducer?

**Comment by tedweishiwang** [comment]
Hi! Thank you for the quick reply. I think the problem is with importing packages. Sorry about the confusion. I will close this.
