### ISSUE TITLE
Relative font sizes of commands and subcommands

### ISSUE THREAD

**Issue by albireox** [click-contrib/sphinx-click#5]
This may be a theme issue, and not a sphinx-click one, but when the documentation is rendered, nested subcommands have the same fontsize as their parents. For instance, in the screenshot, `show_chart` is a subcommand of `ds9`, but their sizes are identical. This makes it hard to know what is a command and what a subcommand. Note that in the sidebar, `show_chart` correctly appears nested under `ds9`.

<img width="1044" alt="screen shot 2017-05-05 at 16 20 05" src="https://cloud.githubusercontent.com/assets/568775/25760852/12912d7e-31af-11e7-8c1b-7df2b96819ad.png">

**Comment by stephenfin** [comment]
That looks like a theme issue alright - I see no such issue with, for example, the [git-pw docs](https://git-pw.readthedocs.io/en/latest/usage.html#git-pw-series).
