### ISSUE TITLE
Sphinx version on requirements.txt

### ISSUE THREAD

**Issue by williamjamir** [click-contrib/sphinx-click#54]
I noticed that in your requirement.txt you are limiting the sphinx version to `1.5>, <2.3`

Are there any known issue or something more serious for this limitation being added?

Otherwise, I would suggest modifying to "sphinx > 1.5", allowing new versions of sphinx to be used as normally.

My motivation for this question is because I'm updating the recipe for conda (https://github.com/conda-forge/sphinx-click-feedstock/pull/6)
 
@stephenfin do you agree with the modification?

**Comment by stephenfin** [comment]
Go for it. Maybe limit to <3.0 though since there might be breaking changes in that version

**Comment by williamjamir** [comment]
Thanks for the quick answer =)

I've changed the conda package, to include this restriction (sphinx>=1.5,<3.0)  and opened a PR to keep the requirements.txt in sync with the conda package ;)
