### ISSUE TITLE
More information for options

### ISSUE THREAD

**Issue by albireox** [click-contrib/sphinx-click#6]
A few things that would be useful to have for the options, if set:

- The type
- The possible values, for multiple choice options
- The default value, if any.
- Whether it's a boolean (`is_flag`)

**Comment by n8pease** [comment]
It would be great if `Parameter.metavar` is used for, or overrides the type.

**Comment by stephenfin** [comment]
As noted in b511f56 and 382d7e5, most of these (possible values, default value, handling metavar) have been resolved now and I don't think the remainder are things we should handle explicitly. Rather, this information should be encoded in help strings.
