### ISSUE TITLE
Misaligned prog name

### ISSUE THREAD

**Issue by WhyNotHugo** [click-contrib/sphinx-click#61]
The name of my program is misaligned by being further indented than it should be. E.g.:

```man
TODOMAN(1)                Todoman               TODOMAN(1)

NAME
       todoman - a simple, standards-based, cli todo

TODO
          todo [OPTIONS] COMMAND [ARGS]...

       Options
```

Note than `todo [OPTIONS` is further right than it should be. For comparison, `man(1)`:

```man
MAN(1)                    Manual pager utils                    MAN(1)

NAME
       man - an interface to the system reference manuals

SYNOPSIS
       man [man options] [[section] page ...] ...
       man -k [apropos options] regexp ...
       man -K [man options] [section] term ...
```

Also, rather than `TODO`, this should say `SYNOPSIS`.

**Comment by stephenfin** [comment]
I think you have the wrong project. *sphinx-click* doesn't do anything special for man pages. You're looking for either *click-man* or *Sphinx* itself.

**Comment by WhyNotHugo** [comment]
Sphinx itself generates man pages based on rst, and I'm using the directive in `sphinx-click`:

```rst
.. click:: todoman.cli:cli
   :prog: todo
   :show-nested:
```

**Comment by stephenfin** [comment]
Gotcha. What I'm saying is that *sphinx-click* doesn't do anything special for that builder. It generates the same rST output regardless of builder and Sphinx converts this to the required output format. We _could_ special case the man builder to generate a different heading, but we don't do this currently and, given *click-man* exists, I don't think we need to.

**Comment by WhyNotHugo** [comment]
`click-man` is a no-go for me since our docs are already written in sphinx, an I want to re-use between the html and man versions as much as possible.

I'll try and figure out how to work around using sphinx-click :)

**Comment by stephenfin** [comment]
Okay. The best option I can think of aside from checking the builder configured at runtime is to allow the output to be templated, ideally using jinja2. Currently that's all generated by hand, so the conversion should be possible, albeit potentially laborious. I'd be happy to accept either approach given sufficient tests, but it's not high enough priority to work on myself, unfortunately.
