### ISSUE TITLE
Hello World repository

### ISSUE THREAD

**Issue by ssomnath** [click-contrib/sphinx-click#66]
Is there a self-contained example demonstrating the use of sphinx-click? For example, I found [this repository](https://github.com/JamesALeedham/Sphinx-Autosummary-Recursion) very helpful for following the procedure to get the recursion to work correctly with sphinx. If there isn't one, I could help put together a Hello World repository with your guidance and assistance.

**Comment by stephenfin** [comment]
The closest thing I'm aware of is the docs. We have a worked example [here](https://sphinx-click.readthedocs.io/en/latest/usage/#example). Is that what you're looking for?

**Comment by ssomnath** [comment]
Thank you for responding very quickly. 

Ah. I see. I was wondering if there were example working repositories I could refer to while I follow the documentation you have put up. I am not super familiar with click and am helping out with putting together documentation. So, an example working repository with all components would have been great. Like I said, I am planning on putting together such a repository using your documentation. If it is fine with you, could I ask you questions as I set up such a hello world repo.

**Comment by stephenfin** [comment]
Sure. We could probably include a sample hello world application in the root of this project if it would be helpful. Feel free to submit a PR if you think this makes sense. I'm happy to answer any questions too

**Comment by ssomnath** [comment]
Thank you very much for your support. I just started putting together a repo here - https://github.com/ssomnath/sphinx-click_Hello-World

**Comment by ssomnath** [comment]
So the [repository](https://github.com/ssomnath/sphinx-click_Hello-World) I put up does indeed work. I added some notes I took down when building the documentation. One could potentially add more complexity for demonstration purposes such as documenting additional groups, etc. Please let me know what you think about this.

**Comment by stephenfin** [comment]
I think we've done as much as we can do here. Thanks for the link to the starter project. I'm sure that will be helpful to others. As I noted previously, if you wishes to include this in the main project then I could help with that but what you have is more than good enough :smile:
