### ISSUE TITLE
Support count=True option references

### ISSUE THREAD

**Issue by SeanDS** [click-contrib/sphinx-click#69]
Currently click options specified with [`count=True`](https://click.palletsprojects.com/en/7.x/options/#counting), useful for verbose flags for example, are not supported in N-length form:

```rst
Specify :option:`-vv` to enable debug output.
```

The above issues the following warning while building with Sphinx:

```
WARNING: unknown option: -vv
```

**Comment by stephenfin** [comment]
I'm afraid this is not something that's within our control. [Sphinx provides the `:option:` role](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option) and we merely reuse it. I suspect you'll have to do without cross-referencing here or work around it with something like:

```rst
Specify `-vv` (:option:`-v`) to enable debug output.
```

**Comment by SeanDS** [comment]
Would this work if `sphinx-click` output additional options in the `.. option` role?

```rst
.. option:: -v, -vv, -vvv

    Enable verbosity.
```

Perhaps the number of options (i.e. 3 for `-vvv`) could be controlled by an option in the `.. click::` role?
