### ISSUE TITLE
ENH allow to exclude some sub-commands automatically

### ISSUE THREAD

**Issue by tomMoral** [click-contrib/sphinx-click#72]
First of all, thanks for this very nice package! It makes the documentation of click based application very easy.

We are developing a command line tool and we have some private sub-commands that we would like to exclude from the doc.
I know that I can select the `subcommands` that are documented using the `:commands:` directive.

However, most sub-commands need to be included in our case so having a easy way to exclude "private" commands would be very nice, either having a `:exclude:` directive or not documenting certain patterns, for instances sub-commands starting with `_`.  WDYT?

**Comment by stephenfin** [comment]
Would it be possible to use [hidden commands](https://click.palletsprojects.com/en/7.x/api/?highlight=hidden#click.Command)? If these commands are truly private you probably want to hide them in the CLI docs (i.e. `--help`) too.

If not, this does sound reasonable and could probably be achieved by replacing the `:commands:` option with `:include:` and `:exclude:` options. I can't promise I'll get to this in the next while but I'd be happy to review a PR if anyone could work on it.

**Comment by tomMoral** [comment]
You are right, `hidden` is what I need and it works well with `sphinx-click` as the command is not displayed. Thanks!

Not sure if the `:exclude:` is really useful as my aim was mainly for private sub-commands and `:hidden:` is better as it also makes it private in for the CLI help. If you think it is not useful, feel free to close this issue. Else, I might give it a try if I get some spare time :).

**Comment by stephenfin** [comment]
Yeah, given `private` exists there's probably no immediate need for this
