### ISSUE TITLE
handle numeric choices

### ISSUE THREAD

**Issue by tmasek** [click-contrib/sphinx-click#75]
https://github.com/click-contrib/sphinx-click/blob/54b80c873ce543019097a53f92486d1f3d70d097/sphinx_click/ext.py#L91

The "join()" call in ^^ this ^^ line should probably say ``' | '.join(str(_) for _ in opt.type.choices)`` instead.

Not sure, there may be other related issues, but this is the one that got me..

**Comment by tmasek** [comment]
thanks!

**Comment by domdfcoding** [comment]
The documentation for [click.Choice](https://click.palletsprojects.com/en/8.0.x/api/?highlight=choice#click.Choice) says "All of these values have to be strings." 

Click itself errors when passing integers (see https://github.com/pallets/click/issues/784)
