### ISSUE TITLE
Remove any ANSI escape sequences from cli documentation

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [click-contrib/sphinx-click#77]
Thank you for working on this project, I've used it for a while and it's really slick, kudos.

I have noticed that when [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) are used to denote colour of the text to use when rendering the text in the terminal, they are rendered "as-is". The `sphinx-click` parses the strings using `statemachine.string2lines()`; it does not show any consideration for any eventual escape sequences that may be present -- this results in raw escape sequences text being rendered in the HTML documentation.

I believe it may be beneficial to strip the escape sequences given that it's quite likely developers of the `click` applications may take advantage of custom colorisation of their help documentation that is going to be rendered in the terminal with pretty colours.

To illustrate the problem:

```
os_support = f'\033[94m{os_support}\033[0m'
print(os_support)
print(re.sub(r'\x1b\[([0-9,A-Z]{1,2}(;[0-9]{1,2})?(;[0-9]{3})?)?[m|K]?', '', os_support))
```

![Screenshot 2021-03-16 at 11 59 44](https://user-images.githubusercontent.com/59651540/111305643-1c48bf00-864f-11eb-92a0-acc30c56340b.png)

The rendered HTML docs for the colorised epilog:

![Screenshot 2021-03-16 at 12 01 07](https://user-images.githubusercontent.com/59651540/111305806-4f8b4e00-864f-11eb-98bc-b790bc6c8d4a.png)

Do you think it would be reasonable to strip the escape codes out of any string that is going to be read from the command line documentation (description, subcommands, options, etc) using a regexp such as the one used in the example above? Are there any complications that I may have overseen?

Many thanks.

**Comment by stephenfin** [comment]
This should be doable, hopefully without extra dependencies. Not sure when I'll have a chance to have a look at this but I'd be happy to guide anyone that was interested in fixing this.

**Comment by stephenfin** [comment]
This _should_ be done in 2.7.0. Let me know if there are further tweaks needed.

**Comment by AlexTereshenkov** [comment]
> This _should_ be done in 2.7.0. Let me know if there are further tweaks needed.

Hey @stephenfin thanks a lot for this. Unfortunately, stripping is not done for the epilog and command options - I've raised a PR for this https://github.com/click-contrib/sphinx-click/pull/79 :)
