### ISSUE TITLE
Feature request: Allow mix of click directives and custom sections in docs

### ISSUE THREAD

**Issue by skjoedt** [click-contrib/sphinx-click#78]
I'm having trouble mixing click directives with custom documentation (extended explanations etc.) because click directives are nested under the previous section.

In the use case below I want to have a flat section level:

```restructuredtext
===
CLI
===

.. _prog status:

.. click:: prog.cli.command:status
   :prog: prog status

prog command status
-------------------

See `prog status`_.

.. click:: prog.cli.command:test
   :prog: prog command test
```

Here, I expected to have 

```markdown
# CLI
## prog status
## prog command status
## prog command test
```

but ended up with 
```markdown
# CLI
## prog status
## prog command status
### prog command test
```

Is it possible to add a feature that let's you either control the section level or omit the section entirely, e.g.

```restructuredtext
prog command test
-----------------

.. click:: prog.cli.command:test
   :prog: prog command test
   :nofirstsection:
```

**Comment by stephenfin** [comment]
The `:nested:` option should do the trick. There's lots of information on this and other options [in the docs](https://sphinx-click.readthedocs.io/en/latest/usage/).
