### ISSUE TITLE
Support click 8.0.0

### ISSUE THREAD

**Issue by albireox** [click-contrib/sphinx-click#82]
Click 8.0.0 was just released but it seems it makes sphinx-click revert to 2.5.0. I've tested a project forcing both click 8.0.0 and sphinx-click 2.7.1 and it seems to compile fine and cannot see any obvious problems.

**Comment by stephenfin** [comment]
Good spot. Fixed in commit daa249d0f27c7206ec44f5e9f85e05f50381e064 and the forthcoming 3.0.0 release
