### ISSUE TITLE
Cross-referencing `envvar`

### ISSUE THREAD

**Issue by paw-lu** [click-contrib/sphinx-click#92]
```rst
.. click:: nbpreview.__main__:typer_click_object
   :prog: nbpreview / nbp
   :nested: full


:program:`nbpreview / nbp`

:option:`--plain`

:option:`--decorated`

:option:`nbpreview / nbp --plain`

:envvar:`NBPREVIEW_PAGING`
```

<img width="346" alt="Screen Shot 2022-01-27 at 7 20 58 PM" src="https://user-images.githubusercontent.com/30049606/151482013-f8bffb62-44ea-4120-ac4f-1bc656a01f17.png">

Testing out the cross-referencing for this library. I can only get `option` to work correctly and generate a link. I think `program` is not expected to work, but why isn't `envvar` working? The environmental variables are listed on the page, but unlike the other elements, they don't seem to generate an anchor link (no ¶ symbol). Is this an upstream sphinx bug? Want to make sure that I'm using this correctly.

---

Thanks for sharing this work, it's been really useful!

**Comment by stephenfin** [comment]
> Testing out the cross-referencing for this library. I can only get `option` to work correctly and generate a link. I think `program` is not expected to work,

[Unfortunately not, no](https://github.com/sphinx-doc/sphinx/issues/880).

> but why isn't `envvar` working? The environmental variables are listed on the page, but unlike the other elements, they don't seem to generate an anchor link (no ¶ symbol). Is this an upstream sphinx bug? Want to make sure that I'm using this correctly.

Normally [this _would_ work](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-envvar), but we found that envvars [were _extremely_ likely to conflict](https://github.com/click-contrib/sphinx-click/issues/26). As a result, you need to use `ref` instead and reference it with `{command_name}-{param_name}-{envvar}`. In your example, this would probably look like:

```rst
:ref:`nbpreview-paging-NBPREVIEW_PAGING`
```

**Comment by stephenfin** [comment]
We should document this...

**Comment by paw-lu** [comment]
Thank you so much @stephenfin for both the explanation and documentation. Really appreciated!

**Comment by paw-lu** [comment]
This isn't working for me actually.

```rst
# Usage2

.. click:: nbpreview.__main__:typer_click_object
   :prog: nbpreview
   :nested: full

:program:`nbpreview / nbp`

:option:`--paging`

:option:`nbpreview --paging`

:ref:`nbpreview-paging-NBPREVIEW_PAGING`

```

<img width="493" alt="Screen Shot 2022-01-28 at 8 48 16 PM" src="https://user-images.githubusercontent.com/30049606/151647736-3c4e94c5-3b85-478c-8938-051e2450353f.png">

**Comment by paw-lu** [comment]
Update, explictly wrapping the reference in `< >` seems to generate the link, but I don't really know why to be honest.

```rst
Usage2
======

.. click:: nbpreview.__main__:typer_click_object
   :prog: nbpreview
   :nested: full

:program:`nbpreview`

:option:`--paging`

:option:`nbpreview --paging`

:ref:`foo <nbpreview-paging-NBPREVIEW_PAGING>`

```

<img width="493" alt="Screen Shot 2022-01-28 at 9 28 00 PM" src="https://user-images.githubusercontent.com/30049606/151648773-f7bb1642-cf7a-4ff2-832d-6711ff2e3124.png">

But, while the link refers to the expected address—`usage2.html#nbpreview-paging-nbpreview-paging`, this link takes me nowhere.

**Comment by paw-lu** [comment]
> But, while the link refers to the expected address—`usage2.html#nbpreview-paging-nbpreview-paging`, this link takes me nowhere.

Actually these links work as expected when clicked from another page.

```rst
Another page
============

.. This takes me to the envvar definition!
:ref:`foo <nbpreview-theme-NBPREVIEW_THEME>`

```

So something else is going on there.
