### ISSUE TITLE
Consider adding the sphinx-extension GitHub topic

### ISSUE THREAD

**Issue by jdillard** [click-contrib/sphinx-click#97]
:wave:  You might consider adding the `sphinx-extension` topic, https://github.com/topics/sphinx-extension, to the repo so it is easier for others to find on the GitHub ecosystem. I saw you had `sphinx-plugin`, but this one is way more popular as there are currently 180 other sphinx extensions that use that topic and this would be a great addition to the list.

**Comment by stephenfin** [comment]
Good idea. Done.
