### ISSUE TITLE
:nested: full doesn't work anymore

### ISSUE THREAD

**Issue by FreeHarry** [click-contrib/sphinx-click#99]
The flag `:nested: full` doesn't work anymore since version 4.0.1. 
Sub-commands from additional groups are not documented.

Before this version there was no problem.

**Comment by stephenfin** [comment]
Fixed in 4.0.2.

**Comment by damienrj** [comment]
Any chance to yank 4.0.1 version to make this bug more visible?

**Comment by stephenfin** [comment]
Sure, done :wastebasket:
